version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: film-location-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: film_locator
    ports:
      - "5432:5432"
    volumes:
      - film_locator_data:/var/lib/postgresql/data

volumes:
  film_locator_data:
